### ISSUE TITLE
Insert Pictures

### ISSUE THREAD

**Issue by vincentzcm** [MuTsunTsai/slidev-theme-frankfurt#1]
I want to know how to insert pictures in markdown for this template. Can you give me an example code to insert pictures

**Comment by MuTsunTsai** [comment]
There's nothing special about this theme when it comes to adding images. It's the same way for any Slidev presentations. Some examples can be seen here:
https://sli.dev/guide/syntax.html#static-assets
If you have questions about how to use Slidev in general, I would suggest posting questions on the official [Discussion](https://github.com/slidevjs/slidev/discussions).

**Comment by vincentzcm** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我会尽快给你回复。
