### ISSUE TITLE
h1 title disappears in the first page

### ISSUE THREAD

**Issue by gz-gary** [MuTsunTsai/slidev-theme-frankfurt#2]
My slides.md looks like this:

```
---
theme: frankfurt
infoLine: true # on by default, can be turned off
author: 'noname' # shows in infoLine
title: 'notitle' # shows in infoLine
date: '2024/05/09' # shows in infoLine, defaults to the current date
---

# title
```

However, when I open it in slidev, I see only a big blue bar across the first page without any words on it. Is this a bug?

**Comment by MuTsunTsai** [comment]
Hello and thanks for reporting. I was unable to reproduce the issue, however. The following is the screenshot of mine using your sample, and everything looks fine. Could you upload a minimal repo that reproduces the issue to GitHub or somewhere so that I can investigate further?

![image](https://github.com/MuTsunTsai/slidev-theme-frankfurt/assets/39870664/c47ea704-5cb5-4832-81d8-ea2667a99dc0)

**Comment by MuTsunTsai** [comment]
@gz-gary Ah, I see now. This issue only happens in Slidev 0.49beta, where they've changed the HTML structure that makes my CSS cease to work. I've patched it in v1.0.6 and it should work fine now.

**Comment by gz-gary** [comment]
Hello! I am trying to use v1.0.6. But there is still something strange. My slides.md here:
```
---
theme: frankfurt
infoLine: true # on by default, can be turned off
author: 'noname' # shows in infoLine
title: 'title' # shows in infoLine
date: '2024/05/09' # shows in infoLine, defaults to the current date
---

# Intro

---

# next page
```
And I am running slidev with:
```
sudo npx slidev
```
As expected, I see the title:
![image](https://github.com/MuTsunTsai/slidev-theme-frankfurt/assets/149811884/a01f70f0-3c62-4b9a-b86a-606dfd006cbe)
without the infoLine. I refresh the page in my browser(firefox) and it turns to be a blue bar across the page again:
![image](https://github.com/MuTsunTsai/slidev-theme-frankfurt/assets/149811884/d52c7b82-f848-42e2-82a0-0974ca9b9831)
Then I restart slidev. This time I remove a line in the header:
```
---
theme: frankfurt
infoLine: true # on by default, can be turned off
author: 'noname' # shows in infoLine
date: '2024/05/09' # shows in infoLine, defaults to the current date
---

# Intro

---

# next page
```
And the infoLine appears correctly. But when I add the line back to the header, the infoLine still appears correctly while the title turns to be a blue bar across the page again.
![image](https://github.com/MuTsunTsai/slidev-theme-frankfurt/assets/149811884/fbba8a3c-ecba-4acf-a5f5-c558b2adc20a)
Should I use slidev of previous versions to avoid this?

**Comment by MuTsunTsai** [comment]
@gz-gary Which version are you using? I've tested v1.0.6 against all versions of Slidev from 0.48.9 (the supposed stable release) to 0.49.0-beta.4, and your slides all work properly.

**Comment by gz-gary** [comment]
@MuTsunTsai  I am using theme of v1.0.6 and Slidev of 0.49.0-beta.5. I cannot reproduce the bug right now. It seems that I do not cleanup my browser cache. Everything now works correctly.
