### ISSUE TITLE
Further Intro to Latex use in component 

### ISSUE THREAD

**Issue by Fisher669** [MuTsunTsai/slidev-theme-frankfurt#3]
<Item title="The key estimation equation is:">
this works by comparing the outcomes of the treated and control groups before and after the policy.

    $$ Y_{it} = \beta_0 + \beta_1 (Treat_i \times Post_t) + \eta X_{it} + \sigma_i + \gamma_t + Z_{rt} + Trend_t + \varepsilon_{it} $$

</Item>
well , i cannot get the promising latex outcome

**Comment by Fisher669** [comment]
well solved! sry to disturb!
I want to know to change colors if i wanted (just fork your work, but i dont know how to apply my tem), i am not familar with npm manger

**Comment by Fisher669** [comment]
![image](https://github.com/user-attachments/assets/e99f19fb-183a-457a-aefd-e7b960c40813)
The headline seems to cover the titile i needed, but in your document it doesn't happens

**Comment by MuTsunTsai** [comment]
@Fisher669 Maybe it's because the page content is too much. What if you break it into two pages?

To change color or other styling, you don't have to fork the theme. You can just add custom stylesheets to your slides: https://sli.dev/custom/directory-structure#style
